2019-07-01 18:10:25,800 - Log.py - ERROR - 接口为：'bserver/record'，方法为：test_jrshujixiangqingye
参数为：body:test_jrshujixiangqingye
params:
错误信息为:
2019-07-01 18:10:27,396 - Log.py - ERROR - 接口为：'bserver/record'，方法为：test_jrshujixiangqingye
参数为：body:test_jrshujixiangqingye
params:
错误信息为:
2019-07-01 18:10:43,675 - Log.py - ERROR - 接口为：'bserver/record'，方法为：test_bangdingzhifubao
参数为：body:test_bangdingzhifubao
params:{"type":"01","aliPay":"ceshi","userName":""}
错误信息为:
2019-07-01 18:11:46,972 - Log.py - ERROR - 接口为：'bserver/record'，方法为：test_chakantixianlishi
参数为：body:test_chakantixianlishi
params:{"type":"01"}
错误信息为:
2019-07-01 18:11:51,787 - Log.py - ERROR - 接口为：'bserver/record'，方法为：test_jinrutixian
参数为：body:test_jinrutixian
params:{"type":"00"}
错误信息为:
2019-07-01 18:12:06,217 - Log.py - ERROR - 接口为：'bserver/record'，方法为：test_tixianxiadan
参数为：body:test_tixianxiadan
params:{"type":"00","seqNum":"1","channel":"alipay","users":{"moIMEI":"86603936330893","deviceId":"test","clientId":"test"}}
错误信息为:
2019-07-01 18:12:07,817 - Log.py - ERROR - 接口为：'bserver/record'，方法为：test_tuichuxiaoxizhongxin
参数为：body:test_tuichuxiaoxizhongxin
params:{"type":"01"}
错误信息为:
2019-07-01 18:12:20,837 - Log.py - ERROR - 接口为：'bserver/record'，方法为：test_shujizhiding
参数为：body:test_shujizhiding
params:{"bookCode":"MY_7860","code":"2"}
错误信息为:
2019-07-01 22:15:45,488 - Log.py - ERROR - 接口为：'bserver/record'，方法为：test_yuedujilu
参数为：body:test_yuedujilu
params:{"fType":"00","tagCode":"31","listCode":"0045","bookCode":"123","bookName":"123","chapterCount":123,"startTime":"20181106121000","readTime":123}
错误信息为:HTTPConnectionPool(host='test.gaokaoceshi.cc', port=80): Max retries exceeded with url: /bserver/record (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114ff0cc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
2019-07-01 22:15:47,058 - Log.py - ERROR - 接口为：'bserver/record'，方法为：test_yuedujilu
参数为：body:test_yuedujilu
params:{"fType":"00","tagCode":"32","listCode":"0045","bookCode":"123","bookName":"123","chapterCount":123,"startTime":"20181106121000","readTime":123}
错误信息为:HTTPConnectionPool(host='test.gaokaoceshi.cc', port=80): Max retries exceeded with url: /bserver/record (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114db2198>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
2019-07-01 22:15:48,614 - Log.py - ERROR - 接口为：'bserver/record'，方法为：test_yuedujilu
参数为：body:test_yuedujilu
params:{"fType":"00","tagCode":"20","listCode":"0046","bookCode":"123","bookName":"123","chapterCount":123,"startTime":"20181106121000","readTime":123}
错误信息为:HTTPConnectionPool(host='test.gaokaoceshi.cc', port=80): Max retries exceeded with url: /bserver/record (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114ff0c50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
2019-07-02 02:22:31,458 - Log.py - ERROR - 接口为：'bserver/record'，方法为：test_bangdanxiangqing
参数为：body:test_bangdanxiangqing
params:
错误信息为:HTTPConnectionPool(host='test.gaokaoceshi.cc', port=80): Max retries exceeded with url: /bserver/store?topType=07&page=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115906898>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
2019-07-02 02:22:33,012 - Log.py - ERROR - 接口为：'bserver/record'，方法为：test_bangdanxiangqing
参数为：body:test_bangdanxiangqing
params:
错误信息为:HTTPConnectionPool(host='test.gaokaoceshi.cc', port=80): Max retries exceeded with url: /bserver/store?topType=08&page=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1158667b8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
2019-07-02 06:32:16,550 - Log.py - ERROR - 接口为：'bserver/record'，方法为：test_shuchengbanner
参数为：body:test_shuchengbanner
params:
错误信息为:HTTPConnectionPool(host='test.gaokaoceshi.cc', port=80): Max retries exceeded with url: /bserver/store?type=00&bannerCode=021 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x114ff0d30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
2019-07-02 08:45:01,484 - Log.py - ERROR - 接口为：'bserver/record'，方法为：test_shudanxiangqing
参数为：body:test_shudanxiangqing
params:
错误信息为:HTTPConnectionPool(host='test.gaokaoceshi.cc', port=80): Max retries exceeded with url: /bserver/store?listCode=0055&page=0&tagCode=20 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115a7ba58>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
2019-07-02 08:45:03,038 - Log.py - ERROR - 接口为：'bserver/record'，方法为：test_shudanxiangqing
参数为：body:test_shudanxiangqing
params:
错误信息为:HTTPConnectionPool(host='test.gaokaoceshi.cc', port=80): Max retries exceeded with url: /bserver/store?listCode=0058&page=0&tagCode=20 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x115a7b5f8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
